[widget]
  [widget.active_window]
    title_scroll = "on_hover"
  [widget.audio_visualizer]
    capsule = true
    show_when_idle = false
  [widget.clock]
    format = "{:%-I:%M %p}"
  [widget.control-center]
    capsule = true
    capsule_opacity = 1
    capsule_radius = 9.0
  [widget.date]
    format = "{:%b %d, %Y}"
  [widget.gap]
    length = 22.0
    type = "spacer"
  [widget.media]
    capsule = true