[shell]
avatar_path = "/home/muhammadtalha/.face/gibli.png"
clipboard_history_max_entries = 20.0
corner_radius_scale = 1.3500000201165676
font_family = "JetBrainsMono Nerd Font Mono"
polkit_agent = true
telemetry_enabled = true

[shell.animation]
speed = 0.6500000096857548

[shell.panel]
clipboard_placement = "attached"
launcher_categories = false
launcher_placement = "attached"
session_placement = "centered"
transparency_mode = "glass"

[shell.session]

[[shell.session.actions]]
action = "logout"
enabled = true
shortcut = "1"
variant = "default"
  
[[shell.session.actions]]
action = "suspend"
enabled = true
shortcut = "2"
variant = "default"
  
[[shell.session.actions]]
action = "reboot"
enabled = true
shortcut = "3"
variant = "default"
  
[[shell.session.actions]]
action = "shutdown"
enabled = true
shortcut = "4"
variant = "destructive"

[control_center]
sidebar = "full"

[keybinds]
cancel = ["Escape"]
validate = ["Return", "KP_Enter"]

