"$schema" = "https://starship.rs/config-schema.json"

format = """
[](#9A348E)\
$os\
$username\
[](bg:blush fg:plum)\
$directory\
[](fg:blush bg:salmon)\
$git_branch\
$git_status\
[](fg:salmon bg:sky)\
$cpp\
$rust\
[](fg:sky bg:coral_coast)\
$docker_context\
[](fg:coral_coast bg:teal_blue)\
$time\
[ ](fg:teal_blue)\
"""

palette = "pastel"

[username]
show_always = true
style_user = "bg:plum"
style_root = "bg:plum"
format = "[$user ]($style)"
disabled = false

[os]
style = "bg:plum"
disabled = false

[os.symbols]
Arch = "󰣇 "

[directory]
style = "bg:blush"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"coding" = "󰲋 "
"code" = "󰲋 "
"development" = "󰲋 "

[cpp]
symbol = " "
style = "bg:#sky"
format = "[ $symbol ($version) ]($style)"

[docker_context]
symbol = " "
style = "bg:coral_coast"
format = "[ $symbol $context ]($style)"

[git_branch]
symbol = ""
style = "fg:plum bg:salmon"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:plum bg:salmon"
format = "[$all_status$ahead_behind ]($style)"

[rust]
symbol = ""
style = "bg:sky"
format = "[ $symbol ($version) ]($style)"

[time]
disabled = false
time_format = "%R"  # Hour:Minute Format
style = "bg:teal_blue"
format = "[  $time ]($style)"

[palettes.pastel]
white = "#FFFFFF"
tan = "#CC3802"
teal = "#047E84"
plum = "#9A348E"
blush = "#DA627D"
salmon = "#FCA17D"
sky = "#86BBD8"
teal_blue = "#33658A"
coral_coast = "#06969A"
